project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

# tell quarto to read the generated styles
# format:
#   css:
#     - api/_styles-quartodoc.css

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: null
  source_dir: iapt_pathway_model

  # write sidebar and style data
  sidebar: api/_sidebar.yml
  css: api/_styles-quartodoc.css



  sections:
    - title: Set Up Options

      options:
        children: embedded
        include_empty: true

      desc: Class controlling model-level parameters
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - iapt_classes.g

    - title: Entities

      options:
        children: embedded
        include_empty: true

      desc: Entity-level
      contents:
        - iapt_classes.Staff
        - iapt_classes.Patient

    - title: IAPT Pathway Model
      options:
        children: separate
        include_empty: true

      desc: Class and methods controlling the flow of patients through the system
      contents:
        - iapt_classes.Model

    - title: Trial Creation

      options:
        children: separate
        include_empty: true

      desc: Class and methods to run and analyse a trial consisting of multiple model runs
      contents:
        - iapt_classes.Trial
