# iapt_classes_model.Model { #iapt_classes_model.Model }

```python
Model(self, run_number)
```



## Attributes

| Name | Description |
| --- | --- |
| [asst_results_df](iapt_classes_model.Model.asst_results_df.qmd#iapt_classes_model.Model.asst_results_df) |  |
| [cbt_staff_counter](iapt_classes_model.Model.cbt_staff_counter.qmd#iapt_classes_model.Model.cbt_staff_counter) |  |
| [couns_staff_counter](iapt_classes_model.Model.couns_staff_counter.qmd#iapt_classes_model.Model.couns_staff_counter) |  |
| [env](iapt_classes_model.Model.env.qmd#iapt_classes_model.Model.env) |  |
| [patient_counter](iapt_classes_model.Model.patient_counter.qmd#iapt_classes_model.Model.patient_counter) |  |
| [pwp_staff_counter](iapt_classes_model.Model.pwp_staff_counter.qmd#iapt_classes_model.Model.pwp_staff_counter) |  |
| [run_number](iapt_classes_model.Model.run_number.qmd#iapt_classes_model.Model.run_number) |  |
| [staff_results_df](iapt_classes_model.Model.staff_results_df.qmd#iapt_classes_model.Model.staff_results_df) |  |
| [step2_results_df](iapt_classes_model.Model.step2_results_df.qmd#iapt_classes_model.Model.step2_results_df) |  |
| [step2_sessions_df](iapt_classes_model.Model.step2_sessions_df.qmd#iapt_classes_model.Model.step2_sessions_df) |  |
| [step2_waiting_list](iapt_classes_model.Model.step2_waiting_list.qmd#iapt_classes_model.Model.step2_waiting_list) |  |
| [step3_results_df](iapt_classes_model.Model.step3_results_df.qmd#iapt_classes_model.Model.step3_results_df) |  |
| [step3_sessions_df](iapt_classes_model.Model.step3_sessions_df.qmd#iapt_classes_model.Model.step3_sessions_df) |  |
| [step3_waiting_list](iapt_classes_model.Model.step3_waiting_list.qmd#iapt_classes_model.Model.step3_waiting_list) |  |

## Methods

| Name | Description |
| --- | --- |
| [calculate_run_results](iapt_classes_model.Model.calculate_run_results.qmd#iapt_classes_model.Model.calculate_run_results) |  |
| [caseload_builder](iapt_classes_model.Model.caseload_builder.qmd#iapt_classes_model.Model.caseload_builder) |  |
| [cbt_staff_generator](iapt_classes_model.Model.cbt_staff_generator.qmd#iapt_classes_model.Model.cbt_staff_generator) |  |
| [couns_staff_generator](iapt_classes_model.Model.couns_staff_generator.qmd#iapt_classes_model.Model.couns_staff_generator) |  |
| [find_caseload_slot](iapt_classes_model.Model.find_caseload_slot.qmd#iapt_classes_model.Model.find_caseload_slot) |  |
| [generator_patient_referrals](iapt_classes_model.Model.generator_patient_referrals.qmd#iapt_classes_model.Model.generator_patient_referrals) |  |
| [pathway_runner](iapt_classes_model.Model.pathway_runner.qmd#iapt_classes_model.Model.pathway_runner) |  |
| [patient_opt_in](iapt_classes_model.Model.patient_opt_in.qmd#iapt_classes_model.Model.patient_opt_in) |  |
| [patient_step2_pathway](iapt_classes_model.Model.patient_step2_pathway.qmd#iapt_classes_model.Model.patient_step2_pathway) |  |
| [patient_step3_pathway](iapt_classes_model.Model.patient_step3_pathway.qmd#iapt_classes_model.Model.patient_step3_pathway) |  |
| [patient_treatment_generator](iapt_classes_model.Model.patient_treatment_generator.qmd#iapt_classes_model.Model.patient_treatment_generator) |  |
| [pwp_staff_generator](iapt_classes_model.Model.pwp_staff_generator.qmd#iapt_classes_model.Model.pwp_staff_generator) |  |
| [random_normal](iapt_classes_model.Model.random_normal.qmd#iapt_classes_model.Model.random_normal) |  |
| [record_caseload_use](iapt_classes_model.Model.record_caseload_use.qmd#iapt_classes_model.Model.record_caseload_use) |  |
| [replenish_weekly_resources](iapt_classes_model.Model.replenish_weekly_resources.qmd#iapt_classes_model.Model.replenish_weekly_resources) |  |
| [resource_builder](iapt_classes_model.Model.resource_builder.qmd#iapt_classes_model.Model.resource_builder) |  |
| [review_referral](iapt_classes_model.Model.review_referral.qmd#iapt_classes_model.Model.review_referral) |  |
| [run](iapt_classes_model.Model.run.qmd#iapt_classes_model.Model.run) |  |
| [screen_referral](iapt_classes_model.Model.screen_referral.qmd#iapt_classes_model.Model.screen_referral) |  |
| [staff_entity_generator](iapt_classes_model.Model.staff_entity_generator.qmd#iapt_classes_model.Model.staff_entity_generator) |  |
| [step2_group_process](iapt_classes_model.Model.step2_group_process.qmd#iapt_classes_model.Model.step2_group_process) |  |
| [step2_pwp_process](iapt_classes_model.Model.step2_pwp_process.qmd#iapt_classes_model.Model.step2_pwp_process) |  |
| [step3_cbt_process](iapt_classes_model.Model.step3_cbt_process.qmd#iapt_classes_model.Model.step3_cbt_process) |  |
| [step3_couns_process](iapt_classes_model.Model.step3_couns_process.qmd#iapt_classes_model.Model.step3_couns_process) |  |
| [telephone_assessment](iapt_classes_model.Model.telephone_assessment.qmd#iapt_classes_model.Model.telephone_assessment) |  |
| [the_governor](iapt_classes_model.Model.the_governor.qmd#iapt_classes_model.Model.the_governor) |  |
| [top_up_caseloads](iapt_classes_model.Model.top_up_caseloads.qmd#iapt_classes_model.Model.top_up_caseloads) |  |
| [weekly_stats](iapt_classes_model.Model.weekly_stats.qmd#iapt_classes_model.Model.weekly_stats) |  |